excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - news-example/Resources/Generated
  - news-exampleTests
  - news-exampleUITests

identifier_name:
  excluded:
    - id
